import type { ComponentType, GarageSettings, LubeType } from "./garage";

export interface CatalogEntry {
  type: ComponentType;
  label: string;
  defaultKm?: number; // default service interval, km (distance-based)
  defaultDays?: number; // default service interval, days (time-based)
  hasLube?: boolean;
  // Seeded automatically for every bike with the catalog default interval, so a
  // fresh bike starts with the components most riders track (the wear parts) plus
  // the whole-bike calendar reminders, instead of an empty list.
  autoAdd?: boolean;
  // The SEED_VERSION at which this entry began auto-seeding. On a version bump,
  // only entries introduced *after* a bike's recorded seed version are added, so
  // a default the rider deleted under an earlier version isn't resurrected.
  // Required whenever `autoAdd` is set.
  seededSince?: number;
}

// Bumped whenever the set of `autoAdd` components grows, so bikes seeded under an
// older catalog pick up the newly-added defaults exactly once (see
// `ensureDefaultComponents`). v1 seeded only the calendar reminders (torque +
// annual service); v2 added the wear parts (drivetrain, tires, brake pads).
// Each new default carries the version it arrived in via `seededSince`.
export const SEED_VERSION = 2;

const MI = 1.609344; // km per mile

// --- Chain service intervals -------------------------------------------------
// Chain wear is what actually matters (replace ~0.5% for 11/12-spd), but riders
// can't measure that when adding a component, so we pre-fill a researched,
// attribute-aware mileage they can override. The dominant signal a rider knows
// up front is their lube (and, for hot wax, which Silca additive "chip" is in
// the pot), so the heuristic keys off those. Values are in miles — that's how
// the manufacturer/community guidance is published — and converted to km here.
//
// Sources (see README + PR):
// - Wax: Silca Secret Chain Blend hot-melt averages ~250–350 mi per application
//   (we use 320). https://silca.cc/products/secret-chain-wax-blend
// - Wax + EnduranceChip: Silca claims up to ~800 mi; we use a conservative 465.
// - Wax + SpeedChip: race-day additive, ~up to 200 km / 125 mi per Silca.
//   https://silca.cc/products/performance-chips
// - Dry lube: reapply every ~100–150 mi in dry conditions (we use 125).
// - Wet lube: 182 mi. Ceramic: long-life wet lube, ~405 mi (legacy 650 km).
export const LUBE_MI: Record<LubeType, number> = {
  wax: 320,
  dry: 125,
  wet: 182,
  ceramic: 405,
};

// Silca hot-wax additives. They're mutually exclusive (you drop one chip in the
// pot), so the form offers a single picker rather than two checkboxes. Only
// meaningful with `wax`; ignored for other lubes.
export type ChainAdditive = "none" | "endurance" | "speed";
const WAX_ADDITIVE_MI: Record<Exclude<ChainAdditive, "none">, number> = {
  endurance: 465,
  speed: 125,
};
export const ADDITIVE_LABEL: Record<ChainAdditive, string> = {
  none: "None",
  endurance: "Endurance chip",
  speed: "Speed chip",
};

// Smart default chain interval (km) from lube + optional wax additive.
export function chainIntervalKm(lube: LubeType, additive: ChainAdditive = "none"): number {
  const mi = lube === "wax" && additive !== "none" ? WAX_ADDITIVE_MI[additive] : LUBE_MI[lube];
  return mi * MI;
}

// Recover the wax additive from a stored label (it isn't persisted separately).
// Labels are generated by componentLabel(), e.g. "Clean & wax drivetrain
// (Endurance chip)".
export function additiveFromLabel(label?: string): ChainAdditive {
  if (label?.includes(ADDITIVE_LABEL.endurance)) return "endurance";
  if (label?.includes(ADDITIVE_LABEL.speed)) return "speed";
  return "none";
}

// Tires are tracked as a single combined entry on a short inspect-and-inflate
// cadence (pressure bleeds off over ~a week of riding), not a
// replacement-mileage interval. 62 mi ≈ 100 km; we store the exact
// mile-equivalent so the default reads as "62 mi" (and "100 km"). Because this
// cadence is about checking pressure (independent of compound/use), tires don't
// take an attribute-aware replacement default — see #42 discussion / README.
const TIRE_INSPECT_KM = 62 * MI;

// Labels are phrased as the maintenance action ("Clean & wax drivetrain",
// "Inflate and Inspect Tires") rather than the bare part name, so each row reads
// as the task to perform. The drivetrain entry's CATALOG label is just the
// picker text; the stored/displayed label comes from componentLabel().
export const CATALOG: CatalogEntry[] = [
  // Wear parts seeded onto every bike (autoAdd), added in seed v2, with their
  // researched defaults.
  { type: "chain", label: "Drivetrain", defaultKm: chainIntervalKm("wax"), hasLube: true, autoAdd: true, seededSince: 2 },
  { type: "tire", label: "Inflate and Inspect Tires", defaultKm: TIRE_INSPECT_KM, autoAdd: true, seededSince: 2 },
  { type: "brakePads", label: "Brake pads", defaultKm: 2000, autoAdd: true, seededSince: 2 },
  // Other distance-based parts the rider can add as needed.
  { type: "cassette", label: "Cassette", defaultKm: 8000 },
  { type: "chainring", label: "Chainring", defaultKm: 15000 },
  { type: "rotors", label: "Rotors", defaultKm: 10000 },
  // Electronic (Di2) drivetrain. Opt-in — most bikes are mechanical — so these
  // are NOT auto-seeded (no `autoAdd`/`seededSince`). The main/derailleur
  // battery drains per shift, so mileage is a good proxy: Shimano's own
  // worst-case estimate for 12-speed Di2 is ~1000 km per charge (typically
  // 1000–1500 km real-world), and defaulting to the conservative figure
  // reminds the rider to charge slightly early rather than run flat mid-ride.
  // The shifter CR1632 coin cells deplete on a calendar basis — ~2 years for
  // Dura-Ace/Ultegra, up to 3–4 for lower tiers — so a yearly check leaves wide
  // margin before end-of-life. See README + PR for sources.
  { type: "di2Battery", label: "Charge Di2 derailleur battery", defaultKm: 1000 },
  { type: "di2Shifter", label: "Check Di2 shifter batteries", defaultDays: 365 },
  // Whole-bike, calendar-based reminders, seeded automatically since seed v1.
  { type: "torque", label: "Check and torque bolts", defaultDays: 180, autoAdd: true, seededSince: 1 },
  { type: "inspection", label: "Yearly inspection and service", defaultDays: 365, autoAdd: true, seededSince: 1 },
];

export const LUBE_LABEL: Record<LubeType, string> = {
  wax: "Wax",
  dry: "Dry lube",
  wet: "Wet lube",
  ceramic: "Ceramic",
};

export function catalogEntry(type: ComponentType): CatalogEntry {
  return CATALOG.find((c) => c.type === type) ?? CATALOG[0];
}

// The default service interval used to seed a freshly-added component (and the
// auto-added frame reminders). Returns meters for distance-based types and days
// for time-based types. Rider `settings` override the researched catalog
// defaults; for the chain those overrides are per-lube. The wax additive
// heuristic still wins, because picking a chip *is* choosing a specific
// interval — a custom per-lube default only applies to plain (no-chip) wax.
export function defaultInterval(
  type: ComponentType,
  settings?: GarageSettings,
  lube: LubeType = "wax",
  additive: ChainAdditive = "none",
): number {
  const e = catalogEntry(type);
  if (e.defaultDays != null) {
    return settings?.intervals?.[type] ?? e.defaultDays;
  }
  if (e.hasLube) {
    if (lube === "wax" && additive !== "none") return chainIntervalKm(lube, additive) * 1000;
    return settings?.chainIntervals?.[lube] ?? chainIntervalKm(lube, "none") * 1000;
  }
  return settings?.intervals?.[type] ?? (e.defaultKm ?? 0) * 1000;
}

// The label as displayed/stored for a component. The drivetrain reads as the
// product actually used — "Clean & wax drivetrain" for wax, "Clean & lube
// drivetrain" for any oil-based lube — with the hot-wax additive chip (which
// drives the interval) kept in parentheses so it round-trips on edit. Every
// other component uses its catalog label.
export function componentLabel(
  type: ComponentType,
  lube?: LubeType,
  additive: ChainAdditive = "none",
): string {
  if (type === "chain") {
    const base = lube === "wax" ? "Clean & wax drivetrain" : "Clean & lube drivetrain";
    if (lube === "wax" && additive !== "none") return `${base} (${ADDITIVE_LABEL[additive]})`;
    return base;
  }
  return catalogEntry(type).label;
}

/** Whether a component type is tracked on a calendar (days) cadence. */
export function isTimeBased(type: ComponentType): boolean {
  return catalogEntry(type).defaultDays != null;
}
