import { useEffect, useRef, useState } from "react";
import {
  ADDITIVE_LABEL,
  CATALOG,
  LUBE_LABEL,
  catalogEntry,
  chainIntervalKm,
  type ChainAdditive,
} from "../lib/catalog";
import type { Component, ComponentType, LubeType } from "../lib/garage";
import { useUnits } from "../UnitsContext";
import { fromMeters, toMeters } from "../lib/units";

interface Props {
  bikeId: string;
  bikeMeters: number;
  initial?: Component; // present = edit mode
  onSubmit: (fields: Omit<Component, "id">) => Promise<void>;
  onCancel: () => void;
}

// Parse a free-text numeric input; blank/invalid -> 0.
const num = (s: string) => {
  const n = parseFloat(s);
  return Number.isFinite(n) ? n : 0;
};

// Recover the wax additive from a saved label (it isn't persisted separately).
// Labels are generated by this form, e.g. "Chain (Wax + Endurance chip)".
const additiveFromLabel = (label?: string): ChainAdditive => {
  if (label?.includes(ADDITIVE_LABEL.endurance)) return "endurance";
  if (label?.includes(ADDITIVE_LABEL.speed)) return "speed";
  return "none";
};

export function ComponentForm({ bikeId, bikeMeters, initial, onSubmit, onCancel }: Props) {
  const { units } = useUnits();
  const isEdit = !!initial;

  const [type, setType] = useState<ComponentType>(initial?.type ?? "chain");
  const [lube, setLube] = useState<LubeType>(initial?.lube ?? "wax");
  // Wax-only additive; drives the pre-filled interval but isn't persisted (the
  // resulting interval is). On edit, recover it from the saved label so we don't
  // silently strip the chip from the label on save.
  const [additive, setAdditive] = useState<ChainAdditive>(() => additiveFromLabel(initial?.label));
  const [brand, setBrand] = useState<string>(initial?.brand ?? "");
  const [psiFront, setPsiFront] = useState<string>(
    initial?.psiFront != null ? String(initial.psiFront) : "",
  );
  const [psiRear, setPsiRear] = useState<string>(
    initial?.psiRear != null ? String(initial.psiRear) : "",
  );
  // Strings so the fields can be cleared/edited freely.
  const [interval, setInterval] = useState<string>(() =>
    String(
      Math.round(fromMeters((initial?.intervalMeters ?? chainIntervalKm("wax") * 1000) || 0, units)),
    ),
  );
  const [wear, setWear] = useState<string>(() =>
    initial ? String(Math.round(fromMeters(Math.max(0, bikeMeters - initial.installMeters), units))) : "",
  );
  const [saving, setSaving] = useState(false);

  // Convert the typed values if the mi/km toggle changes while the form is open.
  const prevUnits = useRef(units);
  useEffect(() => {
    const prev = prevUnits.current;
    if (prev === units) return;
    const convert = (s: string) =>
      s.trim() === "" ? "" : String(Math.round(fromMeters(toMeters(num(s), prev), units)));
    setInterval(convert);
    setWear(convert);
    prevUnits.current = units;
  }, [units]);

  const entry = catalogEntry(type);
  const isTire = type === "tire";

  const defaultIntervalFor = (t: ComponentType, l: LubeType, a: ChainAdditive) => {
    const e = catalogEntry(t);
    const kmVal = e.hasLube ? chainIntervalKm(l, a) : e.defaultKm;
    return String(Math.round(fromMeters(kmVal * 1000, units)));
  };

  const changeType = (t: ComponentType) => {
    setType(t);
    setInterval(defaultIntervalFor(t, lube, additive)); // add mode only (type is locked when editing)
  };
  const changeLube = (l: LubeType) => {
    // Additives only apply to hot wax; drop the chip when leaving wax.
    const a = l === "wax" ? additive : "none";
    setLube(l);
    setAdditive(a);
    if (!isEdit) setInterval(defaultIntervalFor(type, l, a)); // don't clobber a custom interval on edit
  };
  const changeAdditive = (a: ChainAdditive) => {
    setAdditive(a);
    if (!isEdit) setInterval(defaultIntervalFor(type, lube, a));
  };

  async function submit() {
    setSaving(true);
    const lubeLabel =
      lube === "wax" && additive !== "none"
        ? `${LUBE_LABEL[lube]} + ${ADDITIVE_LABEL[additive]}`
        : LUBE_LABEL[lube];
    const label = entry.hasLube ? `${entry.label} (${lubeLabel})` : entry.label;
    try {
      await onSubmit({
        bikeId,
        type,
        label,
        lube: entry.hasLube ? lube : undefined,
        brand: brand.trim() ? brand.trim() : undefined,
        psiFront: isTire && num(psiFront) > 0 ? num(psiFront) : undefined,
        psiRear: isTire && num(psiRear) > 0 ? num(psiRear) : undefined,
        installMeters: Math.max(0, bikeMeters - toMeters(num(wear), units)),
        intervalMeters: toMeters(num(interval), units),
      });
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="form">
      <div className="form-title">{isEdit ? "Edit component" : "Add component"}</div>

      <div className="form-row">
        <label>Component</label>
        <select
          value={type}
          disabled={isEdit}
          onChange={(e) => changeType(e.target.value as ComponentType)}
        >
          {CATALOG.map((c) => (
            <option key={c.type} value={c.type}>
              {c.label}
            </option>
          ))}
        </select>
      </div>

      {entry.hasLube && (
        <div className="form-row">
          <label>Lube</label>
          <select value={lube} onChange={(e) => changeLube(e.target.value as LubeType)}>
            {(Object.keys(LUBE_LABEL) as LubeType[]).map((l) => (
              <option key={l} value={l}>
                {LUBE_LABEL[l]}
              </option>
            ))}
          </select>
        </div>
      )}

      {entry.hasLube && lube === "wax" && (
        <div className="form-row">
          <label>Wax additive</label>
          <select
            value={additive}
            onChange={(e) => changeAdditive(e.target.value as ChainAdditive)}
          >
            {(Object.keys(ADDITIVE_LABEL) as ChainAdditive[]).map((a) => (
              <option key={a} value={a}>
                {ADDITIVE_LABEL[a]}
              </option>
            ))}
          </select>
        </div>
      )}

      <div className="form-row">
        <label>Brand / model</label>
        <input
          type="text"
          placeholder={isTire ? "e.g. Continental GP5000" : "optional, e.g. Shimano XT"}
          value={brand}
          onChange={(e) => setBrand(e.target.value)}
        />
      </div>

      {isTire && (
        <div className="form-row">
          <label>Target PSI</label>
          <div className="form-pair">
            <input
              type="number"
              inputMode="numeric"
              placeholder="front"
              aria-label="Front PSI"
              value={psiFront}
              onChange={(e) => setPsiFront(e.target.value)}
            />
            <input
              type="number"
              inputMode="numeric"
              placeholder="rear"
              aria-label="Rear PSI"
              value={psiRear}
              onChange={(e) => setPsiRear(e.target.value)}
            />
          </div>
        </div>
      )}

      <div className="form-row">
        <label>Service interval ({units})</label>
        <input
          type="number"
          inputMode="numeric"
          value={interval}
          onChange={(e) => setInterval(e.target.value)}
        />
      </div>

      <div className="form-row">
        <label>{isEdit ? `Current wear (${units})` : `Already ridden (${units})`}</label>
        <input
          type="number"
          inputMode="numeric"
          placeholder="0"
          value={wear}
          onChange={(e) => setWear(e.target.value)}
        />
        {isEdit && <div className="form-hint">Set to 0 to reset (e.g. freshly waxed).</div>}
      </div>

      <div className="form-actions">
        <button type="button" className="btn-ghost" onClick={onCancel} disabled={saving}>
          Cancel
        </button>
        <button
          type="button"
          className="btn-primary"
          onClick={submit}
          disabled={saving || num(interval) <= 0}
        >
          {saving ? "Saving…" : isEdit ? "Save changes" : "Add component"}
        </button>
      </div>
    </div>
  );
}
